# Generated by Django 3.2.18 on 2023-04-06 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependenies = [
        ('pretixbase', '0231_auto_20230208_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('request_date', models.DateTimeField(null=True)),
                ('approve_date', models.DateTimeField(null=True)),
                ('complete_date', models.DateTimeField(null=True)),
                ('fail_date', models.DateTimeField(null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pretixbase.order')),
            ],
        ),
        migrations.CreateModel(
            name='SellRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=32)),
                ('state', models.CharField(max_length=32)),
                ('request_date', models.DateTimeField(null=True)),
                ('complete_date', models.DateTimeField(null=True)),
                ('fail_date', models.DateTimeField(null=True)),
                ('direct_buy_request', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pretix_ticketbourse.buyrequest')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pretixbase.order')),
            ],
        ),
    ]
