# Generated by Django 3.2.19 on 2023-06-11 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pretix_ticketbourse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='blocked',
            field=models.BooleanField(default=False),
        ),
    ]
