# Generated by Django 4.2.9 on 2024-04-23 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('pretix_ticketbourse', '0002_auto_20230611_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrequest',
            name='extends_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='positions',
            field=models.ManyToManyField(related_name='ticketbourse_buy_requests', to='pretixbase.orderposition'),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='pay_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='buyrequest',
            name='abort_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='buyrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='buyrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketbourse_buy_requests', to='pretixbase.order'),
        ),

        migrations.AddField(
            model_name='sellrequest',
            name='positions',
            field=models.ManyToManyField(related_name='ticketbourse_sell_requests', to='pretixbase.orderposition'),
        ),
        migrations.AddField(
            model_name='sellrequest',
            name='abort_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sellrequest',
            name='direct_buy_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_sell_requests', to='pretix_ticketbourse.buyrequest'),
        ),
        migrations.AlterField(
            model_name='sellrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sellrequest',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticketbourse_sell_requests', to='pretixbase.order'),
        ),
    ]
