# Generated by Django 4.2.27 on 2026-03-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pretixbase", "0297_outgoingmail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="locale",
            field=models.CharField(default="en", max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="locale",
            field=models.CharField(default="en", max_length=50),
        ),
    ]
