from django.urls import re_path

from .views import *

urlpatterns = [
    re_path(r"^control/event/(?P<organizer>[^/]+)/(?P<event>[^/]+)/settings/ticketbourse$",
        TicketBourseSettingsView.as_view(),
        name='event.settings.ticketbourse',
    ),
    re_path(r"^control/event/(?P<organizer>[^/]+)/(?P<event>[^/]+)/ticketbourse/stats$",
        TicketBourseStatsView.as_view(),
        name='event.ticketbourse.stats',
    ),
    re_path(r"^control/event/(?P<organizer>[^/]+)/(?P<event>[^/]+)/ticketbourse/manual$",
        ManualCancelApprove.as_view(),
        name='event.ticketbourse.manual',
    ),
    re_path(r"^control/event/(?P<organizer>[^/]+)/(?P<event>[^/]+)/orders/(?P<code>[0-9A-Z]+)/ticketbourse/buy/approve_order$",
        BuyApproveOrderView.as_view(),
        name='control.order.buy_approve_order',
    ),
    re_path(r"^control/event/(?P<organizer>[^/]+)/(?P<event>[^/]+)/orders/(?P<code>[0-9A-Z]+)/ticketbourse/buy/delete_request$",
        BuyDeleteRequestView.as_view(),
        name='control.order.buy_delete_request',
    ),
    re_path(r"^control/event/(?P<organizer>[^/]+)/(?P<event>[^/]+)/orders/(?P<code>[0-9A-Z]+)/ticketbourse/buy/block$",
        BuyBlockRequest.as_view(),
        name='control.order.buy_block_request',
    ),
    re_path(r"^control/event/(?P<organizer>[^/]+)/(?P<event>[^/]+)/orders/(?P<code>[0-9A-Z]+)/ticketbourse/buy/unblock$",
        BuyUnblockRequest.as_view(),
        name='control.order.buy_unblock_request',
    ),
    re_path(r"^control/event/(?P<organizer>[^/]+)/(?P<event>[^/]+)/orders/(?P<code>[0-9A-Z]+)/ticketbourse/sell/cancel_order$",
        SellCancelOrderView.as_view(),
        name='control.order.sell_cancel_order',
    ),
    re_path(r"^control/event/(?P<organizer>[^/]+)/(?P<event>[^/]+)/orders/(?P<code>[0-9A-Z]+)/ticketbourse/sell/delete_request$",
        SellDeleteRequestView.as_view(),
        name='control.order.sell_delete_request',
    ),
]

event_patterns = [
    re_path(r'^order/(?P<order>[^/]+)/(?P<secret>[A-Za-z0-9]+)/ticketbourse/buy$',
        RequestBuyView.as_view(),
        name='event.order.ticketbourse.buy'),
    re_path(r'^order/(?P<order>[^/]+)/(?P<secret>[A-Za-z0-9]+)/ticketbourse/buy/cancel$',
        CancelBuyView.as_view(),
        name='event.order.ticketbourse.cancel_buy'),
    re_path(r'^order/(?P<order>[^/]+)/(?P<secret>[A-Za-z0-9]+)/ticketbourse/sell$',
        RequestSellView.as_view(),
        name='event.order.ticketbourse.sell'),
    re_path(r'^order/(?P<order>[^/]+)/(?P<secret>[A-Za-z0-9]+)/ticketbourse/sell/cancel$',
        CancelSellView.as_view(),
        name='event.order.ticketbourse.cancel_sell'),
]
